[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#004b8d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f4f7"
textColor = "#222222"
font = "sans serif"
